enable: false
licenses:
  license: free
  secret_key:

project:
  platform: github
  token:
  org:
    name: MCEngine-Engine
    url: https://github.com/MCEngine-Engine
  repo:
    name: essential
    url: https://github.com/MCEngine-Engine/essential
    issue:
      url: https://github.com/MCEngine-Engine/essential/issues
  website:
    url: https://mcengine-website.github.io/essential

# Database support
# - sqlite
# - mysql
# - postgresql
database:
  type: sqlite

  sqlite:
    path: essential.db

  mysql:
    host: localhost
    port: "3306"
    name: mcengine
    user: root
    password: ""

  postgresql:
    host: localhost
    port: "5432"
    name: mcengine
    user: postgres
    password: ""
